line-length: false
header-increment: false
heading-increment: false
no-duplicate-header: false
no-duplicate-heading: false
no-inline-html:
  allowed_elements:
    - 'a'
no-multiple-blanks: false
no-trailing-punctuation: false
single-h1: false
