sudo: false
language: node_js
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - node_modules
  yarn: true
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper.*$/
before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile
install:
  - travis_retry yarn install
before_script: greenkeeper-lockfile-update
script:
  - commitlint-travis
  - 'echo "Skipping build/tests."'
after_script: greenkeeper-lockfile-upload
after_success:
  - npm run semantic-release
